name: OSX

on:
  workflow_call:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]
        architecture: [ x86 , x64 ]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: initalize github repo
        uses: actions/checkout@v3

      - name: install GCC suite
        run: |
          brew install gcc
          brew install lcov
          brew reinstall gcc

      - name: get compilers
        run: |
          ls /usr/bin
          ls /usr/local/bin
          which gcc
          which g++
          which gfortran
          gcc --version

      - name: Configure CMake (GCC)
        run: |
          cmake -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DCMAKE_FORTRAN_COMPILER=/usr/local/bin/gfortran -B ${{github.workspace}}/build -DBUILD_TESTS=ON -DCMAKE_VERBOSE_MAKEFILE=ON

      - name: Build (GCC)
        run: |
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
