name: openMTPK Core

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest , macos-latest ]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: initalize github repo
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: install deps
        run: | 
          sudo apt install lcov
          pip install gcovr
      
      - name: setup CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.24'

      - name: build openMTPK lib
        run: | 
          LD_LIBRARY_PATH=/usr/local/lib
          mkdir build && cd build
          cmake ..
          make
          make install

      - name: openMTPK examples
        run: sh -x all.sh

