name: openMTPK Core

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest , macos-latest ]
    defaults:
      run:
        shell: bash -l {0}
        
        env:
          # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
          BUILD_TYPE: Release

          steps:
            - uses: actions/checkout@v3

            - name: Configure CMake
              # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is 
              # only required if you are using a single-configuration generator such as make.
              run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

            - name: Build
              # Build your program with the given configuration
              run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

            - name: Test
              working-directory: ${{github.workspace}}
              run: make run-tests

            - name: openMTPK examples
              run: sh -x all.sh

