name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: initalize github repo
        uses: actions/checkout@v3

      - name: code coverage
        uses: codecov/codecov-action@v3
      

