name: Codecov analysis

on:
  workflow_call:

jobs:
  changes:
    name: Check changes to source code and documentation 
    runs-on: 'ubuntu-20.04'
    # Declare outputs for next jobs
    outputs:
      src_changed: ${{ steps.check_file_changed.outputs.src_changed }}
    steps:
    - uses: actions/checkout@v2
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: 2
    - shell: pwsh # the example this is adopted from makes use of PowerShell
      id: check_file_changed
      run: |
        # diff HEAD W/ previous commit
        $diff = git diff --name-only HEAD^ HEAD
        # check if specific folder with file extentions has changes
        $SourceDiff = $diff | Where-Object { $_ -match '^modules/' -or $_ -match '^include/' -or $_ -match '^docs/' }
        $HasDiff = $SourceDiff.Length -gt 0
        Write-Host "::set-output name=src_changed::$HasDiff"


  build-and-test:
    needs: [ changes ]
    if: needs.changes.outputs.src_changed == 'True'
    runs-on: [ ubuntu-latest ]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: initalize github repo
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: install deps
        run: | 
          sudo apt-get install lcov cmake gfortran cppcheck doxygen
      - name: Configure
        run: |
          sudo apt-get install libgtest-dev && 
          cd /usr/src/gtest && 
          sudo cmake CMakeLists.txt && 
          sudo make && 
          cd /usr/src/gtest/lib &&
          sudo cp -a libgtest.a libgtest_main.a /usr/lib && 
          sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && 
          sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a 

      - name: gtest on openGPMP
        run: |
          mkdir build && cd build
          # run tests and populate lcov.info file
          cmake -S ../ -DBUILD_TESTS=ON -DBUILD_COV=ON && make
      
      - name: Generate HTML Analysis & Unit Test Coverage
        run: |
          doxygen
          make docs-testing
          make docs-analysis

      - name: Codecov Sync
        uses: codecov/codecov-action@v3
        with:
          files: .coverage/lcov.info
          name: codecov-umbrella
          functionalities: fixes
          verbose: true

      - uses: actions/upload-artifact@v3
        with:
          name: LCOV_FILES
          #path: .coverage/lcov.info
          path: docs/

