name: Fortran

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:
    name: Test Fortran API
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3

      - name: Install GNU Fortran
        uses: modflowpy/install-gfortran-action@v1

      - name: Test openMTPK Fortran API
        runs: |
          cd Fortran/lib &&
          make verify

