name: Merge rolling into main

on:
  schedule:
    - cron: "*/2 * * * *"
  push:
    branches:
      - rolling


jobs:
  nightly-merge:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.MTPK_BOT_ACCT }}


    - name: Merge rolling -> main
      uses: robotology/gh-action-nightly-merge@v1.4.0
      with:
        stable_branch: 'rolling'
        development_branch: 'main'
        push_token: 'BOT_TOKEN' 
        user_name: mtpk-bot
        user_email: akiel.aries@gmail.com
        allow_ff: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BOT_TOKEN: ${{ secrets.MTPK_BOT_ACCT }}

