name: Merge rolling into main

on:
  schedule:
    - cron: "*/2 * * * *"
  push:
    branches:
      - rolling

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge rolling -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: main
          message: '#ROLLING: Nightly Merge'
          github_token: ${{ secrets.GITHUB_TOKEN }}

