name: Merge rolling into main

on:
  schedule:
    - cron: "*/2 * * * *"
  push:
    branches:
      - rolling


jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Merge rolling branch
        run: |
          git config user.name mtpk-bot
          git config user.email akiel.aries@gmail.com
          git merge --no-ff rolling -m "Merge rolling branch into main by mtpk-bot"
      - name: Push changes to main branch
        uses: ad-m/github-push-action@master
        with:
          branch: main

