name: Merge rolling into main

on:
  schedule:
    - cron: "*/2 * * * *"
  push:
    branches:
      - rolling


jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Merge rolling into main branch
      run: |
        git config --global user.name "mtpk-bot"
        git config --global user.email "akiel.aries@gmail.com"
        git merge --no-ff --no-edit origin/rolling
        git push -f origin main

