name: Merge rolling into main

on:
  schedule:
    - cron: "*/2 * * * *"
  push:
    branches:
      - rolling


jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main
    - name: Checkout rolling branch
      uses: actions/checkout@v2
      with:
        ref: rolling
        fetch-depth: 0
    - name: Merge rolling into main branch
      run: |
        git config user.name "mtpk-bot"
        git config user.email "mtpk-bot@example.com"
        git merge --no-ff --no-edit rolling
        git push origin main

