name: Merge rolling into main

on:
  push:
    branches:
      - rolling
  schedule:
    - cron: "*/1 * * * *"


env:
  # replace "github_username" with your GitHub username
  # replace "github.com/username/repo.git" with your GitHub repo path
  # do NOT replace ${{secrets.GITHUB_TOKEN}}, GitHub will take care of it
  MY_REPO: https://akielaries:${{secrets.GITHUB_TOKEN}}@github.com/akielaries/openMTPK.git

  # replace "long-lived_branch_name" with your branch name
  MY_BRANCH: rolling

  # replace it with the path to master repo
  MASTER_REPO: https://github.com/akielaries/openMTPK.git

  # replace "master" with your master branch name
  MASTER_BRANCH: main

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.MTPK_BOT_ACCT }}

    - name: Merge with main
      run: |
        git config user.name "mtpk-bot"
        git config user.email "akiel.aries@gmail.com"
        git switch main
        git merge rolling
        git push
