name: Merge rolling into main

on:
  schedule:
    - cron: "*/2 * * * *"
  push:
    branches:
      - rolling

env:
  # replace "github_username" with your GitHub username
  # replace "github.com/username/repo.git" with your GitHub repo path
  # do NOT replace ${{secrets.GITHUB_TOKEN}}, GitHub will take care of it
  MY_REPO: https://akielaries:${{secrets.GITHUB_TOKEN}}@github.com/akielaries/openMTPK.git

  # replace "long-lived_branch_name" with your branch name
  MY_BRANCH: main

  # replace it with the path to master repo
  MASTER_REPO: https://github.com/akielaries/openMTPK.git

  # replace "master" with your master branch name
  MASTER_BRANCH: rolling

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out...
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MTPK_BOT_USER }}
          ref: main

      - name: merge
        run: |
          git merge remotes/origin/rolling -m "#ROLLING: Merge from rolling -> main"
          git push origin main


