name: Test AM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: initalize github repo
        uses: actions/checkout@v3
      
      - name: Configure
        run: |
          sudo apt-get install libgtest-dev && 
          cd /usr/src/gtest && 
          sudo cmake CMakeLists.txt && 
          sudo make && 
          sudo cp -a *.a /usr/lib && 
          sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && 
          sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
      
      - name: Set up
        run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror" ..

      - name: Install gtest
        run: make 

      - name: gtest on Arith 
        run: make test-arith

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Upload to coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools cpp-coveralls
          coveralls -E ".*CMakeFiles.*" -E ".*tests/.*.cpp.*" --exclude "venv" --exclude "build/_deps"

