name: Test Wheel Build

on:
  push:
    branches: 
    - '**'
  workflow_call:

jobs:
  sdist_raspy: 
    name: DIST - Raspberry Pi OS Lite
    runs-on: ubuntu-latest
    steps:
      -
        name: initalize github repo
        uses: actions/checkout@v3
      
      -
        name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      
      -
        name: Test sdist on RPI OS ARMv8 Image
        uses: pguyot/arm-runner-action@v2
        id: build_image
        with:
          base_image: raspios_lite_arm64:latest
          commands: |
            uname -a
            echo ::set-output name=uname::$(uname -a)
            apt-get update
            apt-get install -y python3 python3-distutils python3-pip python3-apt python3-dev
            apt-get install -y pkg-config
            apt-get install -y swig
            pip install --upgrade pip setuptools wheel
            cd Python
            python3 setup.py build_ext --inplace sdist bdist_wheel --plat-name=manylinux1_x86_64
            cp ../samples/python/*.py dist
            cd dist
            unzip *.whl
            for f in *.py; do python3 "$f"; done
  
      -
        name: Get platform info
        run: |
          uname -a
          echo ::set-output name=uname::$(uname -a)
